//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEF_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public string Answer_ID { get; set; }
        public string Answer_Content { get; set; }
        public string Puzzle_ID { get; set; }
    
        public virtual Puzzle Puzzle { get; set; }
    }
}
