//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEF_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string Stu_ID { get; set; }
        public string Lec_ID { get; set; }
        public string Topic_ID { get; set; }
        public string Comment_ID { get; set; }
        public string Comment_Content { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
